### ISSUE TITLE
Translations not working

### ISSUE THREAD

**Issue by benhartwich** [gnotaras/wordpress-creative-commons-configurator#5] opened 2015-11-03 11:08 UTC
Hi,

a few translations are not working, for example the most important "This work is licensed under a ...". A n update of the given german po files with the current pot language file removes many items, which could not be translated any more. Perhaps you can send me a working pot file that I can translate it in german.

Regards,

**Comment by gnotaras** [comment] 2015-11-03 12:19
Hello Ben,

Thanks for your feedback. If I understand correctly, the translations stopped working after an update? Please let me know of more details about it so I can investigate it further.

Translations are managed in this [CC-Configurator Translations](https://www.transifex.com/codetrax/cc-configurator/) project on the Transifex service. The German translation is fully managed and contributed by the German Team. Feel free to join this team (free registration is required) and further discuss the relevant issue. Unfortunately, I do not speak German, so I cannot comment on the quality of the translated strings. From what I can tell, the translation has stalled. If you are interested in making progress with it, I could give you coordinator privileges on the team.

BTW, about the request you had made on wordpress org a while, I had tried to contact you over Twitter (from my _codetrax_ account), but you didn't seem to notice it at all :-). The page describing where the data is stored is the following: http://www.codetrax.org/projects/wp-cc-configurator/wiki/Data_Storage. If you need more information, please let me know and I'll be glad to help.

George

**Comment by benhartwich** [comment] 2015-11-05 07:12
Hi,

thanks, till now nobody has accept me to work at the german translation team of your plugin.

Regards,

**Comment by gnotaras** [comment] 2015-11-05 07:17
Hello Ben, I've added you to the team with coordinator privileges.

**Comment by benhartwich** [comment] 2015-11-05 10:09
Thanks, I´ve translated nearly the whole plugin. When are these translations updated?

**Comment by gnotaras** [comment] 2015-11-05 18:04
The general rule (by convention) is to automatically include all translations which are >80% complete. But, if you think the current translation is usable and the key parts have been translated, then please let me know when you would like to make a new release.

**Comment by benhartwich** [comment] 2015-11-06 08:18
Fully translated now. You can update if you would like to.

**Comment by gnotaras** [comment] 2015-11-06 21:28
OK, thanks for letting me know. I'll release a new version as soon as possible.

**Comment by gnotaras** [comment] 2015-11-08 19:35
I'm going to close this issue now. If there is more feedback, please feel free to add a comment.

**Comment by benhartwich** [comment] 2015-11-16 07:17
Hi,

the licence text block on frontend is not translated. I´ve installed the latest version. You can have a look at: https://iliastest.intelec.uni-passau.de/wordpress/test-3/

Regards,

**Comment by gnotaras** [comment] 2015-11-16 08:04
Hello Ben,

Will look into this ASAP and see if there have been any changes of the strings.

George

**Comment by gnotaras** [comment] 2015-11-16 13:12
I cannot find an explanation for this issue. It should appear translated... BTW, I uploaded the updated POT file on transifex, but there are no changes in the license templates as you can see.

**Comment by gnotaras** [comment] 2015-11-16 13:42
Will have to do some further checking. If there is something wrong that will have to do with the expansion of the template variable (although still unexplained why)...

I won't be able to work on this in the following days due to other work I have to do, But I'll look into this very soon.

**Comment by gnotaras** [comment] 2015-11-16 16:22
I cannot reproduce the issue. The German translation appears as expected in my tests. Have you set the site's language in the general WordPress settings?

**Comment by benhartwich** [comment] 2015-11-17 08:07
I´ve translated it with WPML (strings translations) and now it works. Perhaps this plugin is causing problems with yours.

**Comment by gnotaras** [comment] 2015-11-17 08:21
Oh I see. In that case, this has nothing to do with my plugin, which just lets wordpress know of its *text domain* regarding translations. The rest of the work is done by wordpress. Most probably (not 100% sure) the translations are not used when a different language is selected through WPML. This only happens if the site language is changed in the wordpress general settings panel.

I'd highly recommend to open a new issue (whenever you have free time) about using the plugin together with WPML with some general details about the workaround you mentioned. I'm very interested in making sure cc-configurator works fine with this popular plugin.

**Closed by gnotaras** 2015-11-17 08:21 UTC
Labels: enhancement
