### ISSUE TITLE
Providing License Information to Google Image Search

### ISSUE THREAD

**Issue by AgnesKarikaturen** [gnotaras/wordpress-creative-commons-configurator#11] opened 2016-03-17 16:27 UTC
First just to say: I don't buy you a coffee, I will buy you a huge steak if your plugin is able to solve my problem and you can tell me how to do it (...in useful time) ;) 

My need is simple:
I am a painter and live-caricaturist and want to build a big collection of my free images, each with this CC license attributed in a RDFa way, so that google & other image search algorithm can read it:
https://creativecommons.org/licenses/by-sa/4.0/

I am working on a test version on my website. After you select an image in the main menu, you get to this Easy Digital Downloads Post, with a big version of the image as featured image (in header) and a small version of the same image, in the middle of the content, between text.

http://www.live-karikaturen.ch/downloads/sonnenbrillensonne-transparent/

(If you want to see the main menu, its here: http://www.live-karikaturen.ch/webshop-gratisbilder-free-cartoon-comic-images/)

I used your plugin. It writes this HTML code in the head of this document:

```
<!-- BEGIN License added by Creative-Commons-Configurator plugin for WordPress -->
<style type="text/css">
p.cc-block { clear: both; width: 90%; margin: 8px auto; padding: 4px; text-align: center; border: 1px solid #cccccc; color: #000000; background-color: #eef6e6; }
p.cc-block a:link, p.cc-block a:visited, p.cc-block a:hover, p.cc-block a:active { text-decoration: underline; color: #000000; border: none;}
.cc-block img, .cc-block a img { display: inline; padding: 8px; text-decoration: none; }
.cc-button { border-width: 0; }
</style>
<link rel="license" type="text/html" href="https://creativecommons.org/licenses/by-sa/4.0/" />
<!-- END License added by Creative-Commons-Configurator plugin for WordPress -->
```

So maybe Google will recognize the whole page as CC, but does it mean, that google will also link the images on the page with the CC license? I don't have the feeling it does, because I already manually put a CC licence code in a sidebar widget and google doesn't seem to link it with the images on this page.

Back to the CC Configurator: 
In the HTML code the image itself is NOT marked with the CC License, even if I choosed in the Wordpress Media Library for both of the images the right license. 

As far as I got it, the License information for the image needs to be in a DIV container, together with the image. A description ist here:
http://markbirbeck.com/2009/08/14/using-rdfa-to-provide-license

Or here directly the code from this Page:

```
<div about="image.jpg">
  <img src="image.jpg">
  <a rel="license" href="http://creativecommons.org/licenses/by-sa/3.0/"
   >Creative Commons Attribution-Share Alike 3.0</a>
</div>
```

Until now I didn't really understand how to use the FILTERS, but on the other it doesn't look for me on a first sight, as if there would be a useful filter for this problem among this.

I already have a lot of images on my website, but no one shows up, if I search for free images licenses / CC licenses in google image search. The only images that are shown are the ones that I have put on Wikicommons media, they are marked in the right way (with RDFa?), you can see it in the HTML Code of the second link, the relevant copyright information is directly added to the image:

Google image search for free copyright "Agnes Karikaturen"
https://www.google.ch/search?q=agnes+karikaturen&biw=1644&bih=746&source=lnms&tbm=isch&sa=X&ved=0ahUKEwidx4PSjcjLAhUq1XIKHc0nAfgQ_AUIBigB&dpr=0.9#q=agnes+karikaturen&tbm=isch&tbs=sur:fmc

A correct copyright information linked image from me on Wikicommons, the Copyright information is in line 26 of the HTML code:
https://commons.wikimedia.org/wiki/File:Agnes_Karikaturen_Armenien_Schlacht_von_Sardarapat_Battle_of_Sardarabad_T%C3%BCrkei.jpg

Thank you for your fast answer to tell me if this is possible with your plugin or if this is not possible and I have to ask my professional Web-Programmer friend, to help me with another solution to solve this image free CC RDFa attribution. 

Short: I need that Google recognizes my CC images as CC images.

Thank you for your help
Agnes Karikaturen
www.Live-Karikaturen.ch
Switzerland
 
PS: You can really charge me for a "Steak" ;) You offer a service and if a plugin works and solves my problems, I am ready to pay some $$$ for a premium version.

**Comment by gnotaras** [comment] 2016-03-17 23:30
Hello Agnes,

Thank you for your question.

As far as content is concerned, the plugin currently generally embeds licensing information into it without adding extra licensing metadata for specific elements, eg media.

But, as I see it without having done any research yet, I think your request is doable by using one of the WordPress filter hooks and retrieving the media's licensing data from my plugin. I'll try to look into this tonight and provide some sample code.

Apart from that, this is actually a great idea for an enhancement of the plugin. I'll post more details after I do my research.

About donations, I'm always glad to receive donations, but always as appreciation of the effort than as payment for services or for a commercial product. :) This is because I maintain the plugin in my free time, so it's not possible for me to provide a quality commercial support service. Nevertheless, I try to help users as soon as I have some time to do so. :)

I'll reply back as soon as I do some testing. Thanks for your feedback! :)

George

**Comment by gnotaras** [comment] 2016-03-18 06:20
Hi Agnes,

What I'm posting here is the first version of the code that can add extra licensing metadata for each attached image. WordPress makes filtering the final HTML code as generated by the `caption` shortcode a bit unnecessarily complicated (already filed a bug about a small issue), but the code snippet should work fine.

The general idea about what it does is the following:

1. Enclose the `img` (or `figure` element) in a `<span about="http://example.com/path/to/image.png"> ... </span>` so as to indicate that the licensing metadata is about the image. I chose `span` instead of `div` so as to avoid any issues with the theme's CSS (has happened a few times with another plugin of mine). This can easily be changed in the code.
2. Embed a `<link rel="license" type="text/html" href="http://example.com/licence.html" />` inside the `span` block. This is not visible to humans. Currently this is *commented out* as possibly unnecessary. I'll keep it as a reminder.
3. Add the hyperlink with `rel="license"` within the `span` block. If a `figcaption` element exists (only generated on themes with HTML5 support), which contains the image caption, then a link to the license page is appended like this ` (CC0 1.0)`. On the contrary, if a `figcaption` element is missing (themes without HTML5 support), it just appends a HTML link to the license page exactly as you posted above.

A simpler approach would be to include the `about` attribute inside the license hyperlink, but that does not leave much room for experimentation with extra metadata.

This is an interesting feature and I'll be working on it in the upcoming days/weeks (time permitting) and hopefully make it an enhancement of the plugin.

The following should work at this point, but some time (days/weeks) might be required before the images are indexed with proper licensing.

Also, since I haven't tested it myself yet, your feedback about how it goes will be greatly appreciated!

The code is the following. You can place it in the theme's `functions.php` or in a custom plugin as shown [here](http://www.codetrax.org/projects/wp-cc-configurator/wiki/Customization#Custom-Plugin) (if you need help with this please let me know):

```php
// Add licensing metadata on a per image basis.
function bccl_image_tag_with_licensing( $dummy, $attr, $content ) {
    // Attachment ID
    if ( ! isset($attr['id']) ) {
        return $content;
    }
    // Find the attachement id from $attr['id'] (format: attachment_ID)
    $id_str = str_replace('attachment_', '', $attr['id']);
    if ( ! is_numeric($id_str) ) {
        return $content;
    }
    $id = absint($id_str);
    // Plugin options
    $options = get_option('cc_settings');
    if ( $options === false ) {
        return $content;
    }
    // License data
    $image = get_post( $id );
    $license_slug = bccl_get_content_license_slug( $image, $options );
    if ( empty($license_slug) ) {
        return $content;
    }
    $license_data = bccl_get_license_data( $license_slug );
    if ( empty($license_data) ) {
        return $content;
    }
    $license_url = $license_data['url'];
    if ( empty($license_url) ) {
        return $content;
    }
    $license_name_short = $license_data['name_short'];
    if ( empty($license_name_short) ) {
        $license_name_short = 'license';
    }

    // Find image URL.
    if ( preg_match('#<img.* src="([^"]+)"#', $content, $matches) ) {
        // First try regex on the $content
        $image_url = $matches[1];
    } else {
        // Otherwise, use the URL of the full image size.
        $main_size_meta = wp_get_attachment_image_src( $id, 'full' );
        $image_url = $main_size_meta[0];
    }
    if ( empty($image_url) ) {
        return $content;
    }

    // Currently it's not possible to filter the final HTML output of img_caption_shortcode().
    // So, here we first remove our current function for the filter hook, then run
    // img_caption_shortcode() to get the default final HTML output and then process
    // it and add our licensing metadata.
    // See about this method: https://core.trac.wordpress.org/ticket/29832#comment:1

    remove_filter('img_caption_shortcode', __FUNCTION__, 10, 3);

    $html = img_caption_shortcode( $attr, $content );
    if ( empty($html) ) {
        return $content;
    }

    add_filter('img_caption_shortcode', __FUNCTION__, 10, 3);

    // Process HTML

    // Embed a link element. Currently commented out as possibly unnecessary.
    //$html = str_replace('<img ', '<link rel="license" type="text/html" href="' . esc_url($license_url) . '" /><img ', $html);

    // Append hyperlink with rel="license".
    if ( strpos($html, '</figcaption>') !== false ) {
        // If the figure html element contains a figcaption element,
        // then we add the HTML hyperlink at the end of it.
        // Construct license hyperlink using short name
        $license_hyperlink = ' (<a rel="license" title="' . esc_attr($license_data['name'])  . '" href="' . esc_url($license_url) . '">' . esc_attr($license_name_short) . '</a>)';
        $html = str_replace('</figcaption>', $license_hyperlink . '</figcaption>', $html);
    } else {
        // Just append a link to the license page
        // Construct license hyperlink using full license  name
        $license_hyperlink = '<a rel="license" title="' . esc_attr($license_data['name'])  . '" href="' . esc_url($license_url) . '">' . esc_attr($license_data['name']) . '</a>';
        $html .= $license_hyperlink;
    }

    // Enclose all HTML in our span element about the image
    $html = '<span about="' . esc_url( $image_url ) . '">' . $html . '</span>';

    return $html;

}
add_filter('img_caption_shortcode', 'bccl_image_tag_with_licensing', 10, 3);
```

Apart from browsing your artwork (great work, pure talent!), I also checked the source code of your web site and noticed that `figure` and `figcaption` elements are not generated for the images. I'm not really expert on themes, but this possibly means that the html5-caption feature is not enabled in your theme. This is fine, but it means that, after placing the above code, a hyperlink using the full license name as anchor text will appear under the image. Any suggestions for improvement about it are very welcome.

Please feel free to post any questions or suggestions. Sometimes it takes a while before I reply.

Best Regards,
George

**Comment by gnotaras** [comment] 2016-03-18 06:31
Now that I re-think about it, some special logic regarding images released with _all rights reserved_ should be added. This is going to be done in a second release.

**Comment by gnotaras** [comment] 2016-03-22 09:15
Hi Agnes,

The above code has been incorporated into the plugin with some changes as an experimental feature. I had been working on another feature which lets the user attribute the work to a different creator and these two features work nicely together. However, there is still some work to be done due to some issues with how WordPress generates the HTML output of the caption/video/audio shortcodes. I expect to release 1.8.16 by the end of the week.

Once the new release is out, please remove the code above from the `functions.php` file and enable the relevant option (_Separate Media License_) in the plugin settings `Settings -> License`.

Feedback is very welcome.

Best Regards,
George

**Comment by gnotaras** [comment] 2016-03-28 16:59
Hello Agnes,

I've finally managed to make the new release (small issues have been delaying it). I recommend removing the code snippet above from the `functions.php` file and use the relevant option (_Separate Media License_) in the plugin settings `Settings -> License`.

This feature is still marked as experimental. We have to wait for a while and see if this is enough for Google to index the images with proper licensing.

Any suggestion or correction is very welcome.

I'm now going to close this issue. I've started a new one (#12) for general discussion and feedback about this feature.

Also, please feel free to post any questions.

George

**Comment by gnotaras** [comment] 2016-03-29 00:24
On a second thought, I think I'll leave this issue open until it is certain that Google picks the image licenses correctly.

**Comment by AgnesKarikaturen** [comment] 2016-03-29 20:30
Dear George

Thank you so much for your **superfriendly & ultrafast support & help**. I am speechless really, not even 2 weeks and you published an user friendly for my specific request, thats just amazing!!! Especially because this CC topic is quite complicated and there seems to be no alternative to your plugin, beside of the "do it yourself"-solution...

We tried it out but don't get any result in the HTML Code on the website. There is still just the Header with the CC information, but no extra information with the picture. I made this testpage:

http://www.live-karikaturen.ch/testseite-cc-lizenz/

In Settings > Licence I chosed "seperate media license"
At the media library the specific image "WurmNadja-W-AgnesKarikaturen-927x1080-testbild" I see the "License this work" field, where the default license is "CC BY-SA 4.0) what is correct, the other fields (Additional terms and conditions, Force creator attribution) are empty.

Until now google doesn't show any new CC images. I don't think the HTML Code from the testsite from above is correct. I guess the image CC licensing information is still missing. Am I doing something wrong? Should I add the code to the functions.php instead to check if there is a difference in the HTML code from this test-website?

First I tried you new plugin update on posts & existing images but I didn't worked (at least I think it doesn't), then I made this testpage above to check it.

I am confused, because I think you checked the new plugin update. What am I doing wrong? Do you need any other informations? 

My wordpress theme should use HTML 5 ("Built with HTML5 and CSS3")
http://themeforest.net/item/sunday-a-complete-photographer-wp-theme/10694939

Among all plugins I use the following:

- Creative Commons Configurator *lol*
- Easy Digital Downloads (and a lot of add-on plugins for this)
- Easy Watermark
- Essential Grid
- Post Snippets
- Redux Framework
- TablePress
- Udinra All Image Sitemap
- WaspThemes - Yellow Pencil Pro
- WP Fastest Cache
- Yoast SEO

Thank you so much your help. Best wishes - and don't worry, I won't forget the XL coffee.

**Comment by gnotaras** [comment] 2016-03-30 03:17
Hi Agnes,

I noticed that the extra licensing metadata was missing from your images, but I assumed that you had been busy and didn't have the time to work on it.

As far as CC-Configurator configuration is concerned, the following should be done in the plugin settings at `Settings -> License`:

 * Set a default license. Please choose a Creative Commons license for the test.
 * Enable the _Separate Media License_ option.

From what I understand, you have already done this.

After this is done, any image that is added to the post content using the `caption` shortcode (the `Add Media` dialog adds images in this way but it can also be done manually) or the featured image should have licensing information.

> In Settings > Licence I chosed "seperate media license"
> At the media library the specific image "WurmNadja-W-AgnesKarikaturen-927x1080-testbild" I see the "License this work" field, where the default license is "CC BY-SA 4.0) what is correct, the other fields (Additional terms and conditions, Force creator attribution) are empty.

Yep, that seems perfectly fine..

> Among all plugins I use the following:

I don't think any of the plugins listed above interfere with this..

> Thank you so much your help. Best wishes - and don't worry, I won't forget the XL coffee. 

Lol, the coffee is totally up to you. I would help anyway. Besides, this was a very nice idea! :-)

I'm quite certain this has to do with WordPress because while implementing this feature I encountered numerous inconsistencies regarding the way the media HTML code is filtered. I actually filed a few bug reports as well. I'll try to recheck this, but it definitely works in my test environment. Hmm..

Could you please do the following:

 1. Edit a post.
 1. While at the post edit screen, switch the editor to _Text_ instead of _Visual_.
 1. Locate the part which contains the `caption` shortcode which adds the image to the post.
 1. Copy it and please paste it here on github. Alternatively, you could copy all the HTML code from the post editor and paste it here.

If for any reason you don't want to paste anything publicly, please feel free to email it to me at the following address: `gnot@g-loaded.eu`

I'll try to do some more testing and reply back with more info.

George

**Comment by gnotaras** [comment] 2016-03-30 05:19
OK, I think I've identified the problem and I'll try to describe it as briefly as possible.

When editing a post and use the `Add Media` dialog to insert an image to the content, WP inserts an `img` element, for instance (case A):

```
<img src="myimage.png" />
```

If the image has a caption, then WP inserts the code like this (case B):

```
[caption ... ... ]<img src="myimage.png" /> My image caption[/caption]
```

My test media library contains only images which have a caption filled in, which means that when inserted to the post, the code looks like the one in case B.

The plugin filters the processing of the `caption` shortcode (does the same with the `video` and `audio` shortcodes) and adds the licensing information. For example, adds the following:

```html
<div ... about="MEDIA_FILE_URL">
    NON_VISIBLE_LICENSING_METADATA
    HTML_OF_ACTUAL_MEDIA_FILE
    MEDIA_CAPTION  +  VISIBLE_LICENSING_METADATA
</div>
```

The plugin works this way in order to generate the licensing information at run time according to the license that has been set in the _License_ box in the post edit screen or according to the default license that has been set in the plugin settings.

The same logic is used for the license of the content of the post. The licensing metadata is not added to the post editor, but instead generated and appended to the post content at run time.

This is done in order to avoid hard coding any licensing information to the post or media files.

In case of images that do not have a caption, WordPress does not enclose them in a `caption` shortcode, which means that CC-Configurator cannot interefere at runtime and append the licensing metadata.

There are 3 solutions for this problem and each one has its pros and cons:

1) Add a caption text to every image, so that the `img` element is enclosed in a `caption` shortcode when the image is inserted into the post. Alternatively, I could make the plugin force wordpress to insert the images in the editor enclosed in a `caption` shortcode, even if there is no caption set.

Pros: The licensing metadata will be automatically added at runtime.
Cons: Existing images in the posts cannot be automatically enclosed in `caption` shortcode, but they have to be reinserted to the post.

2) Filter the post content at runtime, locate the `img` elements (`figure` element as well) determine the ID of the attachment and retrieve and add the licensing information.

Pros: The licensing metadata will be automatically added at runtime.
Cons: Needs a lot of testing to make sure that it is done correctly and still there might be cases it won't work as expected.

3) Make the plugin add the final HTML code containing the licensing information inside the post.

Pros: It'll work with or without image captions.
Cons: Hard coding the licensing information means that even if the license changes at the attachment edit page, it is not going to change in the post which contains the image. Although this might seem OK, it can lead to problems and it is definitely against the logic of the plugin of not hardcoding anything but add the licensing metadata at run time.

My recommendation would be solution 1, but I would like to experiment a bit with 2 as well.

What to do to make it work at this point:

Add an image caption while inserting the image to the post. WP will enclose the `img` in a `caption` shortcode and CC-Configurator will add the licensing metadata at run time.

In order to force WordPress enclose the `img` element in a `caption` shortcode even if you don't set a caption while inserting the image to the post, you can add the following code in the `functions.php` file of the theme:

```php
function bccl_separate_licensing_on_images__force_caption_shortcode( $html, $id, $caption, $title, $align, $url, $size, $alt ) {
    if ( empty($caption) ) {
        return '[caption id="' . $id . '" align="align' . $align     . '" width="' . $width . '"]' . $html . ' ' . $caption . '[/caption]';
    }
    return $html;
}
add_filter('image_send_to_editor', 'bccl_separate_licensing_on_images__force_caption_shortcode', 10, 8);
```

This is only for testing. I'm not sure if this code will finally be added to the plugin.

I hope all this is not confusing. Your thoughts and general feedback about all of the above are greatly appreciated.

George

**Comment by AgnesKarikaturen** [comment] 2016-03-30 12:26
Dear George
 
Thank you again for your :100:% astonishing, first class, Triple A, answer! :) 

Already before I did your explained steps: Set a default license. Please choose a Creative Commons license for the test, Enable the Separate Media License option.

I insert all pictures with the Wordpress "Add Media" Function.

I went to the Text-Editor of the Testsite (). I copied the code for the image:

`<img class="alignleft size-full wp-image-3204" src="http://www.live-karikaturen.ch/wp-content/uploads/2016/03/WurmNadja-W-AgnesKarikaturen-927x1080-testbild.png" alt="Testbild für CC Lizenz Plugin" width="927" height="1080" />`

So I guess this are not big news for you. I try now your suggested workaround in the next answer. Because of optical layout reasons I can't use a caption text for each picture. Obviously my website would be overfilled with captiontext then. But actually, in the "worst" case, I could use a caption text for a specific part of the website, fortunately excatly there, where I need the CC Google Research functions the most. So the solution looks close now. Your plugin is really essential for that specific part of my website, like it it will be for any public image hosting site.

I will tell you detailed results, as soon as we did anything and could check google for CC image search results. 

Thank you & best wishes  from Switzerland to Greece
Agnes
_
PS: Your city already help my family once, when my ancestors had to escape from Turkey to survive the Armenian Genocide in 1915. They found help in Thessaloniki and lived there for many years._

**Comment by gnotaras** [comment] 2016-03-30 13:44
Hi Agnes,

> Because of optical layout reasons I can't use a caption text for each picture. Obviously my website would be overfilled with captiontext then. But actually, in the "worst" case, I could use a caption text for a specific part of the website, fortunately excatly there, where I need the CC Google Research functions the most.

I see. I thought that a visible text about the license was also needed. It is possible to omit the visible license text by also adding the following (in addition to the code snippet above):

```php
add_filter('bccl_enable_visible_media_license_metadata', '__return_false');
add_filter('bccl_enable_visible_featured_media_license_metadata', '__return_false');
```

The surrounding `caption` shortcode is still needed in the post editor, so that my plugin can intercept the generation of the image HTML and insert the licensing information.

So here are the steps to test this:

1) Insert the code snippets of my last two messages in the `functions.php` file. The complete code to add is the following:

```php
function bccl_separate_licensing_on_images__force_caption_shortcode( $html, $id, $caption, $title, $align, $url, $size, $alt ) {
    if ( empty($caption) ) {
        if ( ! preg_match( '/width=["\']([0-9]+)/', $html, $matches ) ) {
            return $html;
        }
        $width = $matches[1];
        return '[caption id="' . $id . '" align="align' . $align     . '" width="' . $width . '"]' . $html . ' ' . $caption . '[/caption]';
    }
    return $html;
}
add_filter('image_send_to_editor', 'bccl_separate_licensing_on_images__force_caption_shortcode', 10, 8);

add_filter('bccl_enable_visible_media_license_metadata', '__return_false');
add_filter('bccl_enable_visible_featured_media_license_metadata', '__return_false');
```

2) Edit a post and use the `Add Media` dialog to **insert** an image to the post **without** adding any caption.

3) Save the post and view the post page. The expected result is to see the image **exactly** as before (without any visible licensing info), but if you check the HTML source code the licensing metadata has been added.

I would **highly recommend** doing this **only for some test images and not for the entire media** library yet, until we are finally certain about what is the best way to do this.

I'll also experiment with solution 2 (as mentioned above) at some later time and reply back with more info.

> PS: Your city already help my family once, when my ancestors had to escape from Turkey to survive the Armenian Genocide in 1915. They found help in Thessaloniki and lived there for many years.

Oh I see! Makes me sad to hear stories about those times in history and about how people had to change their lives. Glad Thessaloniki has been a friendly place for your family! I came to Thessaloniki for studies, but now I live here for over 15 years. Nice city and good people. Best wishes to Switzerland too! :-)

Also thanks for your ideas and feedback about this feature. Helps me make the right decisions about how it should be implemented.

I'll reply back with more info about solution 2.

George

**Comment by gnotaras** [comment] 2016-03-30 14:43
I'm doing some initial testing about solution 2 and, although it could work fine in many cases, it is still possible that in some other cases it will fail to match the needed image or image+caption HTML. So, I don't really think this is a good way to do it.

My thoughts are to stick with solution 1 and keep intercepting the `caption` shortcode and embedding the licensing metadata this way.

Adding an actual caption text to the image is not really required. The only thing that is needed is to enclose images (`<img ... src="..." ... />`) in the `[caption]...[/caption]` shortcode. For instance:

```
[caption]<img ... src="..." ... />[/caption]
```

The snippet above does this automatically whenever you insert an image to the post, regardless of the existence of caption text.

**Comment by gnotaras** [comment] 2016-03-30 15:45
Agnes, I noticed that you enabled the code.

In case you want to customize the template of the licensing information you can use a snippet like the following:

```php
function bccl_custom_cc_media_license_template() {
    // Supports: #media_type#, #creator#, #license#
    return 'Copyright &copy; <em>#creator#</em> under #license#';
}
add_filter( 'bccl_license_text_media_template_cc', 'bccl_custom_cc_media_license_template' );
```

The default is:

```
(#media_type# by <em>#creator#</em> under #license#)
```

If you have any questions, please feel free to ask.

George

**Comment by AgnesKarikaturen** [comment] 2016-03-30 16:00
Again, thank you for the latest postings. :)

Actually you brought me to the idea, that it makes sense to **add captions for the free image part **of my website. It's also an easy way to handle your CCC plugin, then just those images get extra CC information, that have a caption. It's simple this way. The other images, without a caption, dont need the CC code anyway. I don't want them to be found.

So I think, even if this may be useful and important in other cases, I don't even need the version without a caption. But I am happy for your explanations anyway, possible that I will still need to implement your code from above.

I am a bit short in time, but made a first testpage to check the google results. I added on the page editor a caption to both images (if I just add a caption to the image, it doesn't work, I have to add the caption on the specific page with edit image) and I choosed for both images media > edit a CC license with your CCC plugin on this page. The page I have choosen is indexed in google already, so I can check the results.

http://www.live-karikaturen.ch/downloads/grinsewurm-transp/

I also want to do this with the other free image pages on my website.

As far as I can get it from the HTML code, the CC machine code markup works now. That would be great! I am very curious if it will work with google.

I will later try to format the CCC captiontext with the help of the snippet above, make the text smaller and erase the ().

**Comment by gnotaras** [comment] 2016-03-30 21:16
Unfortunately, the solution is still not robust enough because the Wordpress visual editor won't allow a `caption` shortcode on images without any caption text. Switching between the visual and text editor (in the post editing screen) strips the `caption` shortcode if there is no caption text. From what I see there is no standard way to fix this behavior.

I'll have to find another workaround for images without caption.

**Comment by gnotaras** [comment] 2016-03-30 22:40
I think I'm getting somewhere. After some testing I realized that because of the way WordPress does things, there is no "*one size that fits all*" regarding the processing of the images.

So, I went ahead processing images in three different ways according to the following criteria:

1) featured images
2) images with captions, the final HTML code of which is *always* generated using the `caption` shortcode
3) images without captions. The only way to isolate these is to filter the post content (fortunately this was easy for images without caption).

So far it seems to work without problems and without having to deal with the internals of the post editor. It'll also work with existing images without any manual work which is a big plus. I'll do some more testing and, if everything seems OK, I'll make a new release tomorrow.

About the snippets above, none of them will be needed, except for the one that customizes the template of the licensing information.

Thanks for all your feedback. It helped me move to the right direction! :-)

George

**Comment by gnotaras** [comment] 2016-03-31 06:50
Hi Agnes,

I have released v1.8.18, which should work for images with or without a caption and also with featured images. Also options to omit the visible license information from the captions have been added.

None of the snippets above is needed any more, except perhaps for the one that customizes the text template of the licensing information.

Hopefully this release is towards the right direction. However, minor changes may be required. Your feedback is much appreciated. :-)

Please note it might take Google several days before the images are indexed with proper licensing, so we have to wait.

George

**Comment by AgnesKarikaturen** [comment] 2016-03-31 16:39
**Amazing!!! **It already seems to work! Google images show the testpage with the "crazy worm". Before this plugin Google showed just just the colored pictures about Armenia from Wikicommons (which are CC), but now also the CC worm shows up thanx to your CCC plugin:

https://www.google.de/search?q=agnes+karikaturen&espv=2&biw=1343&bih=686&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiHo_rBq-vLAhXHlCwKHdPMBlkQ_AUIBigB#q=agnes+karikaturen&tbm=isch&tbs=sur:fmc

It also works with other keywords on the website, google shows our picture if you search for CC pictures. 

GREAT!!! HUGE THANKS TO YOU GEORGE! That was a **BIG help** for my website.

Now we will continue to optimize layout and work on details and try out modifications, but the basic functions seems to work. Yippieee, Schat Shnorhakaltuyunnnnnnnnnn!

**Comment by gnotaras** [comment] 2016-03-31 17:34
That's great, Agnes! Very glad it works!

The most important part was to make the right decisions about the processing of the media. There are many, many, ways to do things in WordPress, so some experimentation was needed. The media processing now seems efficient enough. The rest is much simpler.

Your feedback about any improvements is very welcome and much appreciated!

George

**Comment by gnotaras** [comment] 2016-04-01 17:54
Agnes, I made some tweaks of the way the HTML code, that is generated by the plugin, integrates with the various themes. Also fixed some issues with image alignment and with the 'wp-caption' class.

I'll try to make a new release very soon.

George

PS: Please note that during the following days it might take a while before I reply back. Feel free to post any feedback.

**Comment by gnotaras** [comment] 2016-04-04 03:48
Hi Agnes,

Thank you very much for donating to the project! I also thank you for your ideas and overall feedback! Everything is much appreciated!

For any questions or suggestions, please feel free to contact me at any time.

About the plugin, I'm preparing yet another release with some improvements regarding the customization of the HTML code that is generated by the plugin.

There are also some issues with the image alignment on AMP pages, but fixing these is beyond my control at this time, so I'll wait to see how the development of the AMP plugin goes and see what has to be done.

Thanks again,
George

**Comment by gnotaras** [comment] 2016-04-05 00:55
Agnes, I just released 1.8.20. At this point, I tried to make everything customizeable and currently there are no planned improvements.

There is a known issue with the alignment of images in AMP pages, but this is caused by the AMP plugin and will be resolved as soon as the AMP plugin developer fixes any issues.

So, for now I'm going to close this issue. Please feel free to add your feedback or reopen it as necessary.

Best Regards,
George

**Closed by gnotaras** 2016-04-05 00:55 UTC
Labels: enhancement, reference

**Comment by AgnesKarikaturen** [comment] 2016-04-09 10:36
## CHANGE THE LINK TO THE "CREATOR ATTRIBUTION NAME" PAGE

Hi George :smiley: :star2:

I added a **caption text** to an image, so that CCC adds the user visible CC copyright information to it (I decided NOT to omit the text). Now there are two URL links in this CCC generated text, one to the author wordpress page ("Creator Attribution Name") and one to the CC license page. The second link (CC license) works fine.

Is it possible to change the automatically generated link to the wordpress author page to another website URL, in my case just "[www.Live-Karikaturen.ch](www.Live-Karikaturen.ch)" ? :pray:

Example for this problem on this page below the first big image with the "crazy worm":
http://www.live-karikaturen.ch/downloads/grinsewurm-transp/

If I click on the "Creator Attribution Name" then I get directed to this blogroll page, what doesn't make sense in my case: 
http://www.live-karikaturen.ch/author/admin/

A simple solution would be to just disable the link and write it as "text only". 
Or I design an /author/admin/ page in Wordpress.

**Comment by gnotaras** [comment] 2016-04-11 07:26
Hi Agnes, I'm sorry for replying so late! :-)

> I decided NOT to omit the text

There is still some research and experimentation to be done to confirm that Google actually supports anything else than the visible link with `rel='license'`. I'm not certain yet, so using the caption is a good idea for the moment!

> Is it possible to change the automatically generated link to the wordpress author page to another website URL, in my case just "www.Live-Karikaturen.ch" ?

Yes, this is possible, but only programmatically. WordPress does not have a _user profile page_, so, by default, the plugin links the author name to the _author archive_. You can customize this by adding the following code in the `functions.php` file:

```php
function bccl_custom_author_url( $default, $post, $creator_format ) {
    return 'http://www.Live-Karikaturen.ch';
}
add_filter( 'bccl_author_url', 'bccl_custom_author_url', 10, 3 );
```

The `return` statement should return the URL of the page you want to link the author.

Please try it and let me know if it works.

George

**Comment by AgnesKarikaturen** [comment] 2016-04-12 15:24
Dear George

It was very easy to do & works perfect. 

Again 12 points to Thessaloniki :grin:, thanx a looot! :star2: 

Best wishes
Agnes

**Comment by gnotaras** [comment] 2016-04-13 13:53
Great, Agnes! Thanks for letting me know! :)
