### ISSUE TITLE
RSS feed producing an error

### ISSUE THREAD

**Issue by markerfreek** [gnotaras/wordpress-creative-commons-configurator#6] opened 2015-11-08 15:09 UTC
After updating to the latest release my RSS feeds stopped working. After running it through a validator, the following error is produced: Namespace prefix creativeCommons on license is not defined
			<creativeCommons:license>http://creativecommons.org/licenses/by-sa/4.0/</cre…

After deactivating the plugin, all seems to be working fine.

Thank you.

Fred Schouten

**Comment by gnotaras** [comment] 2015-11-08 19:30
Hello Fred,

I cannot reproduce this issue. Tried with:

 * ` Include license information in the blog feeds. (Recommended) ` checked in the plugin settings.
 * Checked the RSS 2.0 feed with the validator: https://validator.w3.org/feed/check.cgi

I'll need some detailed instructions about how to reproduce it.

Kind Regards,
George

**Comment by gnotaras** [comment] 2015-11-08 20:02
Also checked the Atom and RDF feeds with the aforementioned validator and I cannot reproduce the problem. May I ask which validator service or offline tool you have used?

**Comment by markerfreek** [comment] 2015-11-08 21:37
George,
Thank you for your reply. After re-activating the plugin, the issue seems to have resolved itself.
I used W3C Feed Validation Service. W3C Feed Validation Service, for Atom and RSS
|   |
|   |  |   |   |   |   |   |
| W3C Feed Validation Service, for Atom and RSSThis is the W3C Feed Validation Service, a free service that checks the syntax of Atom or RSS feeds. The Markup Validation Service is also available if you wish t... |
|  |
| View on validator.w3.org | Preview by Yahoo |
|  |
|   |


It currently throws the following warning/error:

Sorry
This feed does not validate.   
   - line 35, column 3: XML parsing error: <unknown>:35:3: unbound prefix
   -    <creativeCommons:license>http://creativecommons.org/licenses/by-sa/4.0/</ ...
The address of my feed is: http://www.schoutenenterprises.biz/markernieuws/feed
Before I reported the issue the errors were as follows which caused the feed not being read by my RSS reader RRSowl:

Validation Output: 8 Errors
   
   -  Line 35, Column 27: Namespace prefix creativeCommons on license is not defined   			<creativeCommons:license>http://creativecommons.org/licenses/by-sa/4.0/</cre…


   
   -    Thank you,
Fred Schouten

**Comment by markerfreek** [comment] 2015-11-08 21:48
I guess I spoke to soon, the parsing error does cause my feed reader RSSowl and the one on my Yahoo homepage not to read the feed.
Regards,
Fred Schouten

**Comment by gnotaras** [comment] 2015-11-08 22:34
Hi Fred,

> This feed does not validate.
> - line 35, column 3: XML parsing error: <unknown>:35:3: unbound prefix - <creativeCommons:license>http://creativecommons.org/licenses/by-sa/4.0/</ ...
> The address of my feed is: http://www.schoutenenterprises.biz/markernieuws/feed

I see. This error means that the `creativeCommons:....` prefix is unknown to the parser, because the namespace `creativeCommons` has not been defined in the first line of the XML document (the feed). The weird thing is that the plugin automatically sets this namespace if the inclusion of licensing information in the syndicated content has been enabled in the plugin settings...

Checking the XML source of your feed, this namespace declaration is missing for an unknown reason. For example:

`
<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:wfw="http://wellformedweb.org/CommentAPI/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	xmlns:slash="http://purl.org/rss/1.0/modules/slash/"
	xmlns:creativeCommons="http://backend.userland.com/creativeCommonsRssModule"
>
`
Please, notice the last line which defines the `creativeCommons` prefix by linking to the proper RSS module.

Checking the output of the validator for the feed link you posted above, it seems that this namespace definition is missing and I cannot explain which this is happening.

As long as the following line is added:

`
<creativeCommons:license>http://creativecommons.org/licenses/by-sa/4.0/</creativeCommons:license>
`

... the namespace line at the top should be added as well.

Do you use any plugins that manipulate the feeds?

I'm sorry but I cannot find an explanation and most importantly I cannot reproduce the issue. I'll need more details if possible.

George

**Comment by gnotaras** [comment] 2015-11-08 22:43
I made some updates to the previous post mainly because of code formatting and syntax mistakes. I'm not sure if Github sends a notification with the updated content. Please read it on the web page.

**Comment by markerfreek** [comment] 2015-11-08 22:45
George,
I use Featured Images in RSS w/ Size and Position but have used this for almost a year without any issues. 
Other than that, I am not sure what could be causing this.
Regards,
Fred Schouten

**Comment by gnotaras** [comment] 2015-11-08 22:47
I see. If you uncheck the following settings in the CC-Configurator options, does the problem go away?

```
 Include license information in the blog feeds. (Recommended) 
```

George

**Comment by markerfreek** [comment] 2015-11-08 22:50
George,
Unchecking this setting made the issue go away.
Thank you very much.
Regards,
Fred Schouten

**Comment by gnotaras** [comment] 2015-11-08 22:56
This is good to know.

Normally, the use of other plugins that manipulate the feeds should not be a problem. CC-Configurator uses the available filter hooks provided by wordpress to add this extra data to the feeds. Perhaps you should make a report to the author of _Featured Images in RSS w/ Size and Position_, because in this case it seems that it's not CC-Configurator that does something wrong (hopefully).

I've marked this issue as a bug as it requires further investigation, but it doesn't seem to be a bug of the plugin. If you investigate this further, I'd appreciate any extra feedback.

Thanks in advance.

George

**Comment by markerfreek** [comment] 2015-11-08 23:02
George,
I will keep you posted if other info becomes available.
Thank you.
Fred.

**Comment by gnotaras** [comment] 2015-11-08 23:05
Thanks, Fred. Much appreciated.

I also made the issue title more specific according to our above testing results. I hope this is fine.

George

**Comment by gnotaras** [comment] 2015-11-09 00:48
Hi Fred,

After some extensive research I'm quite certain that CC-Configurator is free from problems regarding this issue, so I'm going to remove the 'bug' label from it.

Also, after reviewing the source code of the 'Featured Images in RSS w/ Size and Position' plugin and also after trying it together with CC-Configurator, I still cannot reproduce the issue, so I'll also update the issue title. The two plugins work flawlessly together.

It seems that something else is modifying your feeds and I'm afraid there is nothing I can do more about it. However, I'll keep this issue open for a while and, if no more feedback related to CC-Configurator is submitted, I'll close it.

Feel free to send more feedback about it.

Kind Regards,

George

**Comment by gnotaras** [comment] 2015-11-10 01:50
Hello Fred,

I was not able to reproduce this issue in any way, so I have to close it as invalid. However, further feedback is very welcome.

Kind Regards,
George

**Closed by gnotaras** 2015-11-10 01:50 UTC
Labels: invalid

**Comment by alexriss** [comment] 2016-05-20 12:52
I have the same problem. Using version 1.8.21. The feed validation error message goes away if I uncheck the option "Include license information in the blog feeds. (Recommended)"

**Comment by gnotaras** [comment] 2016-05-26 02:14
Hello Alex,

Thanks for your feedback, but as I've mentioned above there is nothing more I can do for this issue at this time as it is impossible to reproduce it with the provided information.

There is a possibility that another plugin or theme manipulates the feed namespace area after CC-Configurator has added the CC namespace. The only way to troubleshoot this is to switch to a default theme, such as TwentyFifteen, deactivate all your plugins except this one, and then re-enable all other plugins one at a time until you are able to reproduce the issue.

Once you have identified the cause of the problem, please let the other developer(s) know about it.

As far as this plugin is concerned, the only thing that could be changed in the code is the priority of the related actions. In order to check this, please, add the following in the `functions.php` file of the theme and see if the problem is resolved.

```php
remove_action('rdf_ns', 'bccl_add_cc_ns_feed');
remove_action('rss2_ns', 'bccl_add_cc_ns_feed');
remove_action('atom_ns', 'bccl_add_cc_ns_feed');
add_action('rdf_ns', 'bccl_add_cc_ns_feed', 99999);
add_action('rss2_ns', 'bccl_add_cc_ns_feed', 99999);
add_action('atom_ns', 'bccl_add_cc_ns_feed', 99999);
```

If the problem is resolved, then please open a new issue for further discussion. If the above code does not resolve the problem, then I'm sorry to say that there is absolutely nothing I can do about it and my suggestion is to deactivate the setting that has been mentioned above.

George
