### ISSUE TITLE
How to show copyright notices in local language

### ISSUE THREAD

**Issue by dx486** [gnotaras/wordpress-creative-commons-configurator#10] opened 2016-03-05 13:18 UTC
Hello

My wordpress.org site language is set as Turkish. I have installed this plug-in but copyright messages are displayed in English below my posts.

For testing, I set my site language as German, but messages were still shown in English.

I see po and mo files in plugin/languages folder.

Why language files are not in effect?

For clarification, I am not asking about deed file translations. I can do it using wordpress-customizations.php.

Thank you in advance.

**Comment by gnotaras** [comment] 2016-03-05 21:20
Hi @dx486 

I'm sorry for the late reply.

> Why language files are not in effect?

Actually they are in effect, but this happens because the Turkish translation is incomplete at the moment. Please check the following page:

https://www.transifex.com/codetrax/cc-configurator/language/tr/

The Turkish translation right now is only 33% complete and possibly the strings you refer to must be untranslated.

I also checked the German translation and I was surprised to see that despite the fact that completeness is 95%, the licensing messages showed up in English. Then I recalled that I had some manual customizations in place in `wordpress-customizations.php`. As soon as I removed them, the messages were displayed correctly in German. I could not replicate the issue with the German translation.

As a side note, there is always a place for anyone who is willing to submit translations in the CC-Configurator translations project at:

https://www.transifex.com/codetrax/cc-configurator/

As a side note and regarding the Turkish translation, it hasn't been touched for a while. Moreover, I just noticed that the current coordinator has never submitted translations since signing up. So, if you are interested, I could add you to the Turkish translation team (requires free registration at Transifex) as Reviewer and later if you want as Coordinator. Please let me know if you are interested.

Otherwise, I'm out of ideas about how this could be fixed. Unfortunately, I do not speak the Turkish language, so I cannot be much of a help in this case.

Kind Regards,
George

**Comment by gnotaras** [comment] 2016-03-08 16:41
Hello @dx486 

Have you resolved the issue? Should I close this ticket now?

As a side note, I usually close tickets about translations as they should be handled by the translation team at the translations project.

Thanks for you feedback! Also, please feel free to contact me at any time regarding joining the translations project at Transifex.

George

**Comment by dx486** [comment] 2016-03-08 16:56
Hello @gnotaras 

I am working resolving this issue. I want to see "All rights reserved" text in Turkish, for testing. It is translated in Turkish translation po file. However it is shown in my site in English. If you cannot reproduce the situation and you are sure that it is working I guess there is something wrong with my website. I'll check it out. Please close the ticket and thank you for your help.

**Comment by gnotaras** [comment] 2016-03-08 17:18
Hi,

I actually confirm that the Turkish translation of any string might be missing. In my test the text appeared in English.

Also, there is another alternative: to customize the text templates that are used by the plugin. Please check this section:

http://www.codetrax.org/projects/wp-cc-configurator/wiki/Customization#Customize-the-text-templates-of-a-single-license-or-of-a-group-of-licenses

which should give an idea about how to modify the long and short templates for the license text.

I cannot go into the details at this moment, but please feel free to post any questions and I'll reply as soon as possible.

George

**Comment by dx486** [comment] 2016-03-10 15:25
Hi @gnotaras 

I deleted the plugin with all of its data and installed it again. I translated from English to Turkish using only the necessary statement for me ("All rights reserved") using original English po file in Transifex and uploaded translated .po file to my blog. I have changed by blog's language to Deutsch, to Turkish. Unfortunately none of these steps changed the copyright notice's language below my posts from English. My other plugins language files are working properly, so I guess something wrong with this plugin in my blog, but I don't know what it is and I think I can't think of anything else to resolve this issue. I am sorry to keep this issue for long open but I think I am in a dead end. I guess I am giving up for now. Thank you for your help.

**Comment by gnotaras** [comment] 2016-03-10 16:10
Hi @dx486 

There is absolutely no problem with the issue being open. Something does not seem right.. Please give me some days so I can look into this more closely and I'll reply back with more information.

George

**Comment by gnotaras** [comment] 2016-03-10 16:39
Hi @dx486 

I think I've found the problem. The first translator, who had requested the Turkish translation on Transifex, had requested the code `tr`, while [WordPress understands](http://i18n.svn.wordpress.org/) only the `tr_TR` language code.

Can you please try renaming the the Turkish translation files in `/wp-content/plugins/creative-commons-configurator-1/languages` to:

```
cc-configurator-tr.mo  -->  cc-configurator-tr_TR.mo
cc-configurator-tr.po  -->  cc-configurator-tr_TR.po
```

and let me know if it works?

PS: Right now I keep wondering how it had worked in my previous test as mentioned above...

**Comment by dx486** [comment] 2016-03-10 16:46
I have renamed the files. I am sorry but the message is still displayed in English.

**Comment by gnotaras** [comment] 2016-03-10 16:50
From what I noticed, the license text is not translated. Can you please check if the plugin interface shows in Turkish  (`Settings->License`)?

BTW, new translation has been created and the old translated strings were copied:

https://www.transifex.com/codetrax/cc-configurator/language/tr_TR/

May I ask if you are the last translator who joined the Turkish translation team?

**Comment by dx486** [comment] 2016-03-10 17:01
The plugin interface is displayed partly in Turkish, so it seems working there.

I have just obtained cc-configurator-tr_TR.po file from Transifex and uploaded again but it did not help.

Yes, I am the new member of the team.

**Comment by gnotaras** [comment] 2016-03-10 17:04
After renaming the files I can confirm that it works in all my tests. Please make sure that you disable any customization (eg `wordpress-customizations.php`) before testing.

Also please note that any changes to the .po files must be compiled to .mo file. Provided that `gettext` is installed, this can be done with the `msgfmt` utility:

```
msgfmt -c -f -o cc-configurator-tr_TR.mo cc-configurator-tr_TR.po
```

**Comment by gnotaras** [comment] 2016-03-10 17:09
> The plugin interface is displayed partly in Turkish, so it seems working there.

This seems to solve the problem then. Thanks for pointing that out! This has happened one more time with another translation in the past. Perhaps, I should always check the language code from now on.

> I have just obtained cc-configurator-tr_TR.po file from Transifex and uploaded again but it did not help.

It needs to be compiled to .mo file.

> Yes, I am the new member of the team.

That's great! I added you as the coordinator on the `tr_TR` translation. There are actually no special responsibilities for coordinators. If you have any questions, please feel free to contact me.

I'll try to make a new release with the fixed translation very soon. Thank you very much for your feedback.

George

**Comment by dx486** [comment] 2016-03-10 17:18
Hello again @gnotaras 

Thank you for adding me to the team. I'll be happy to help.

I have compiled the .mo file and uploaded, however strangely the message is still in English below my post.

I have disabled all my other plugins, it did not help.

I really wonder where the problem is...

**Comment by gnotaras** [comment] 2016-03-10 17:21
@dx486 Do you happen to have added any customizations in the `functions.php` file of the theme? Could you test with a default theme?

**Comment by dx486** [comment] 2016-03-10 17:28
> Do you happen to have added any customizations in the functions.php file of the theme? 

I think I did not made such a change. Unfortunately using default theme did not help.

**Comment by dx486** [comment] 2016-03-10 17:34
Let me tell you something interesting, I set up a new blog and it does not work there too. Not just for Turkish, also for Deutsch and Italian. License settings page are without problem, but the message below single post is always in English.

**Comment by gnotaras** [comment] 2016-03-10 17:35
Interesting. I'll need some time to think about it. Does this happen with this plugin only?

**Comment by dx486** [comment] 2016-03-10 17:40
I added "Crayon Syntax Highlighter" plugin to the new blog. Yes, its translations work.

**Comment by gnotaras** [comment] 2016-03-10 17:52
Thanks for all the feedback. Please give me some days to investigate this issue.

**Comment by gnotaras** [comment] 2016-03-10 18:17
I set the blog language to Deutsch and currently testing the German translation of the plugin, which is 95% complete, and the license messages are displayed in German. I tested it with WP 4.4.2 and the latest 4.5 beta.

From what I see on Transifex, the relevant strings in the Italian translation have not been translated so it cannot be used for solid conclusions. I'll test it some more with other complete translations during the following days and reply back with more information. In the meantime, any more feedback is greatly appreciated. Thanks for all the information.

**Comment by dx486** [comment] 2016-03-11 10:23
Hello @gnotaras 

Firstly, I have a good news. I have completed Turkish translation.

Secondly, I am in my own humble way trying to find the reason of this issue, despite I am not informed about PHP programming. I have read [this article](http://wordpress.stackexchange.com/questions/80334/how-to-make-a-wordpress-plugin-translation-ready/80335#80335) and gave a `grep -r " _e" *` command in main plugin directory.

Here is its output:

> bccl-admin-panel.php:		<p><label for="<?php echo $this->get_field_id( 'title' ); ?>"><?php _e( 'Title:' ); ?></label> 
> bccl-admin-panel.php:		<label for="<?php echo $this->get_field_id( 'display_in_archives' ); ?>"><?php _e( 'Display in front page and archives', 'cc-configurator' ); ?></label></p>

It seems to me as if the function "_e" is only used in admin panel. Can this be the reason, maybe?

**Comment by gnotaras** [comment] 2016-03-11 15:04
Hi @dx486 

> Firstly, I have a good news. I have completed Turkish translation.

That's fantastic! Thanks for contributing. The translation will ship with the new release! :)

> It seems to me as if the function "_e" is only used in admin panel. It appeared logical to me, as I can only see translations in admin panel. Can this be the reason, maybe?

I'm afraid this is not related. The difference between the `_e()` and the `__()` functions is that the first one prints the translated string while the second one just returns it to the caller function.

I will try to test the translation very soon and reply back with more info.

Thanks again!

**Comment by gnotaras** [comment] 2016-03-11 15:43
Did some testing.. The new Turkish translation (`tr_TR`) seems to work perfectly and I cannot replicate the problem... I'm puzzled about what might be interfering here...

In a [previous post](https://github.com/gnotaras/wordpress-creative-commons-configurator/issues/10#issuecomment-193875566) I had pointed to an example about how to customize the license templates. Is it possible that such a customization is in effect somewhere in a custom plugin or in the `functions.php` of the theme?


A search like the following could be helpful:

```
grep -rsniH "bccl_" *
```

`bccl_` is the prefix that is used in functions and also in filter hook names. If you have attached a filtering function to one of CC-Configurator's filter hooks, it should be in the results.

I'll take a closer look during the weekend, but so far it seems to work for me..

George

**Comment by gnotaras** [comment] 2016-03-11 15:46
Also I'm attaching the translation (.po & .mo files) as they will exist in the next release. Please add them in the following directory and let me know whenever possible if it works:

```
/wp-content/plugins/creative-commons-configurator-1/languages/
```

[languages.zip](https://github.com/gnotaras/wordpress-creative-commons-configurator/files/169475/languages.zip)

**Comment by dx486** [comment] 2016-03-11 15:54
The problem has been solved using the files you provided! :D

**Comment by gnotaras** [comment] 2016-03-11 16:18
@dx486 Very glad to hear that! I had tried everything on my end to reproduce the problem, but it always worked! :D It's good that it has been sorted out. I'll also check if there is anything else that needs fixing and try to make a new release within the weekend. For any question please feel free to contact me. I'll keep this issue open until the next release.

Thanks for contributing!

George

**Comment by gnotaras** [comment] 2016-03-11 16:21
I finally suspect that character encoding might have been the cause of the issue. Not sure though and unfortunately I don't have much time right now to do any research. I will keep a note about this for future reference.

**Comment by dx486** [comment] 2016-03-11 16:37
Hi George!

I am happy that the issue is solved and I can see everything in my language now, well, except one thing, the message of the author, I mean, your message about donation. Why don't you let the translators do their job on that message too? Maybe you can consider this in the next release.

I suspect if other files caused this error, or permission of the folder... I don't know. There is only 2 files now in plugin's /languages folder.

Thank you for working on this issue and I hope you can catch the bug somehow, if this is a bug. I'll be watching this thread until it is closed.

**Comment by gnotaras** [comment] 2016-03-11 17:11
> I am happy that the issue is solved and I can see everything in my language now, well, except one thing, the message of the author, I mean, your message about donation. Why don't you let the translators do their job on that message too? Maybe you can consider this in the next release.

Well, this is intentional because I thought it would be a little awkward for translators to translate this message. And another reason is that I've been thinking about removing it and replacing it with something else which would also cover contributors, but I'm still researching it as microdonations technology is not there yet (I think). :)

About the issue, yeah, there are some things I would like to try in order to find the cause of the problem. I'll try to do this during the weekend.

**Comment by gnotaras** [comment] 2016-03-13 03:01
Hi @dx486 

I did some more testing and I could not reproduce the issue. Permissions are always a possible cause of trouble, so I'll come to the conclusion that it was either due to permissions or character encoding and, since it works for you now, I'll rest my case.. :)

We may not have found the bug, but the good thing is the plugin now has another full translation and also the Turkish translation has a correct language code understood by WordPress.

I will now close this issue. Please feel free to add more feedback or open a new one for any questions/issues.

Best Regards,
George

**Closed by gnotaras** 2016-03-13 03:01 UTC
Labels: bug, translation

**Comment by gnotaras** [comment] 2016-03-18 07:06
Hi, I haven't made a release yet because some other features had been planned, but didn't have enough time to fully implement them yet. I'll try to make the release within the weekend.

George
